version: '3.4'

services:
  html5-web-fundamentals:
    image: "csgrimberg/html5-web-fundamentals:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./:/var/www/html